// Generated by tools/gen-palette.mjs from palette.json. Do not edit.
// Run `node tools/gen-palette.mjs` after changing the palette.

/** One palette slot. `index` is the value stored in `plots.colour_index`. */
export interface PlotColour {
  readonly index: number;
  readonly name: string;
  readonly hex: string;
}

export const PLOT_COLOURS: readonly PlotColour[] = [
  { index: 0, name: 'red', hex: '#FF3B30' },
  { index: 1, name: 'orange', hex: '#FF9F0A' },
  { index: 2, name: 'yellow', hex: '#FFD60A' },
  { index: 3, name: 'cyan', hex: '#64D2FF' },
  { index: 4, name: 'blue', hex: '#0A84FF' },
  { index: 5, name: 'purple', hex: '#BF5AF2' },
  { index: 6, name: 'pink', hex: '#FF375F' },
  { index: 7, name: 'white', hex: '#F2F2F7' },
];

/** Opacity each surface is drawn at, shared with the AR overlay. */
export const PLOT_ALPHA = {
  wallFill: 0.28,
  groundFill: 0.12,
  rail: 1,
  outline: 0.9,
} as const;

/**
 * The colour for a plot. Out-of-range indices wrap rather than throw: a plot
 * that arrives with a bad slot should still be drawn, just not in the slot it
 * asked for.
 */
export function plotColour(colourIndex: number): PlotColour {
  const slot = ((Math.trunc(colourIndex) % PLOT_COLOURS.length) + PLOT_COLOURS.length)
    % PLOT_COLOURS.length;
  return PLOT_COLOURS[slot]!;
}

/** `#RRGGBB` plus an alpha, as a CSS colour MapLibre accepts. */
export function plotColourRgba(colourIndex: number, opacity: number): string {
  const { hex } = plotColour(colourIndex);
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `rgba(${r}, ${g}, ${b}, ${opacity})`;
}
