#!/usr/bin/env node
//
// Generates the plot palette from palette.json.
//
// The palette has to exist in TypeScript and in Kotlin, and the two must agree
// exactly - a plot drawn amber in the web tool and cyan in the AR view is worse
// than having no colours at all. Hand-copying eight hex strings across a
// language boundary is precisely the kind of thing that drifts, so it is
// generated instead.
//
//   node tools/gen-palette.mjs           regenerate
//   node tools/gen-palette.mjs --check   fail if anything is stale (for CI)
//
// palette.json lives here, in the web repo, because that is the repository that
// gets deployed on its own. The Android target is written only when the sibling
// checkout is present, so this stays runnable from a standalone clone.
//
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = JSON.parse(readFileSync(join(root, 'palette.json'), 'utf8'));
const check = process.argv.includes('--check');

const { colours, alpha } = source;
const banner = (comment) =>
  `${comment} Generated by tools/gen-palette.mjs from palette.json. Do not edit.\n` +
  `${comment} Run \`node tools/gen-palette.mjs\` after changing the palette.\n`;

// --- TypeScript --------------------------------------------------------------
const ts = `${banner('//')}
/** One palette slot. \`index\` is the value stored in \`plots.colour_index\`. */
export interface PlotColour {
  readonly index: number;
  readonly name: string;
  readonly hex: string;
}

export const PLOT_COLOURS: readonly PlotColour[] = [
${colours.map((c) => `  { index: ${c.index}, name: '${c.name}', hex: '${c.hex}' },`).join('\n')}
];

/** Opacity each surface is drawn at, shared with the AR overlay. */
export const PLOT_ALPHA = {
  wallFill: ${alpha.wallFill},
  groundFill: ${alpha.groundFill},
  rail: ${alpha.rail},
  outline: ${alpha.outline},
} as const;

/**
 * The colour for a plot. Out-of-range indices wrap rather than throw: a plot
 * that arrives with a bad slot should still be drawn, just not in the slot it
 * asked for.
 */
export function plotColour(colourIndex: number): PlotColour {
  const slot = ((Math.trunc(colourIndex) % PLOT_COLOURS.length) + PLOT_COLOURS.length)
    % PLOT_COLOURS.length;
  return PLOT_COLOURS[slot]!;
}

/** \`#RRGGBB\` plus an alpha, as a CSS colour MapLibre accepts. */
export function plotColourRgba(colourIndex: number, opacity: number): string {
  const { hex } = plotColour(colourIndex);
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return \`rgba(\${r}, \${g}, \${b}, \${opacity})\`;
}
`;

// --- Kotlin ------------------------------------------------------------------
const kt = `${banner('//')}package com.fieldar.plotfinder.core.render

/** One palette slot. [index] is the value stored in \`plots.colour_index\`. */
data class PlotColour(val index: Int, val name: String, val argb: Long)

/**
 * Boundary colours, shared with the web tool through palette.json.
 *
 * Stored as 0xAARRGGBB with full alpha; the renderer applies [PlotAlpha] to the
 * surface it is drawing rather than baking transparency in here.
 */
val PLOT_COLOURS: List<PlotColour> = listOf(
${colours.map((c) => `    PlotColour(${c.index}, "${c.name}", 0xFF${c.hex.slice(1).toUpperCase()}L),`).join('\n')}
)

/** Opacity each surface is drawn at, shared with the web tool. */
object PlotAlpha {
    const val WALL_FILL = ${alpha.wallFill}f
    const val GROUND_FILL = ${alpha.groundFill}f
    const val RAIL = ${alpha.rail}f
    const val OUTLINE = ${alpha.outline}f
}

/**
 * The colour for a plot. Out-of-range indices wrap rather than throw: a plot
 * that arrives with a bad slot should still be drawn, just not in the slot it
 * asked for.
 */
fun plotColour(colourIndex: Int): PlotColour =
    PLOT_COLOURS[((colourIndex % PLOT_COLOURS.size) + PLOT_COLOURS.size) % PLOT_COLOURS.size]
`;

const androidDir = join(
  root, '..', 'plot-ar-android', 'app', 'src', 'main', 'kotlin', 'com', 'fieldar',
  'plotfinder', 'core', 'render',
);

const targets = [
  { path: join(root, 'shared', 'src', 'palette.ts'), content: ts, required: true },
  { path: join(androidDir, 'PlotPalette.kt'), content: kt, required: false },
];

let stale = 0;
for (const { path, content, required } of targets) {
  // A standalone clone of the web repo has no Android checkout beside it. That
  // is a normal state, not a failure: skip rather than write a stray file.
  if (!required && !existsSync(dirname(path))) {
    console.log(`skipped     ${path} (target project not present)`);
    continue;
  }

  let existing = null;
  try {
    existing = readFileSync(path, 'utf8');
  } catch {
    /* not generated yet */
  }
  if (existing === content) {
    console.log(`up to date  ${path}`);
    continue;
  }
  stale++;
  if (check) {
    console.error(`STALE       ${path}`);
  } else {
    writeFileSync(path, content);
    console.log(`written     ${path}`);
  }
}

if (check && stale > 0) {
  console.error(`\n${stale} generated file(s) out of date. Run: node tools/gen-palette.mjs`);
  process.exit(1);
}
